name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USER_USERNAME }}
        password: ${{ secrets.DOCKER_USER_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/baturyusaoezdemir/docker-linter:latest .

    - name: Push Docker Image to ghcr.io
      run: |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/baturyusaoezdemir/docker-linter:latest \
          --push .
